plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.ksp)
    alias(libs.plugins.hilt)
}
android {
    namespace = "com.prism.studio.widget"
    compileSdk = 35
    defaultConfig { minSdk = 26 }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = "17" }

    // DataSources uses LocalDateTime, ZoneId, Duration and Instant.
    // AGP needs BOTH the flag and the dependency below; either one alone silently does nothing.
    compileOptions { isCoreLibraryDesugaringEnabled = true }

    // The generator emits provider classes here alongside the hand-written ones.
    sourceSets["main"].java.srcDirs("src/main/kotlin")
}
dependencies {
    implementation(project(":core:model"))
    implementation(project(":core:render"))
    implementation(project(":core:data"))
    implementation(libs.work.runtime)
    implementation(libs.serialization.json)
    implementation(libs.coroutines.android)
    implementation(libs.hilt.android)
    implementation(libs.hilt.work)
    ksp(libs.hilt.compiler)
    // @HiltWorker is generated by androidx.hilt:hilt-compiler, a separate
    // processor from Dagger's hilt-android-compiler. Both are required.
    ksp(libs.androidx.hilt.compiler)
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.3")
}
