plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.ksp)
    alias(libs.plugins.hilt)
}

android {
    namespace = "com.prism.studio"
    compileSdk = 35

    defaultConfig {
        // The Play identity. Distinct from the Kotlin namespace above, which stays com.prism.studio
        // because it is invisible to users and renaming it risks breaking a working build.
        // This CANNOT be changed after the first publish, so it is set correctly now.
        applicationId = "com.aura.widgets"
        minSdk = 26          // Android 8.0 — covers >97% of devices, gives us RoundedBitmapDrawable + adaptive icons
        targetSdk = 35
        // 1.2.0: procedural wallpapers, Settings tab, aura, native RemoteViews widgets.
        // versionCode = MAJOR*10000 + MINOR*100 + PATCH, per docs/VERSIONING.md.
        versionCode = 10200
        versionName = "1.2.0"
        vectorDrawables.useSupportLibrary = true

    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }

    buildFeatures {
        compose = true
        // AGP 8 no longer generates BuildConfig by default. MainActivity shows the version in
        // Settings, which is what every competitor's settings screen does and users expect.
        buildConfig = true
    }

    lint {
        // A release build must not ship with lint errors. Warnings are allowed but reported.
        abortOnError = true
        warningsAsErrors = false
        checkReleaseBuilds = true
        lintConfig = file("../lint.xml")
        baseline = file("lint-baseline.xml")
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        isCoreLibraryDesugaringEnabled = true   // java.time on API 26 sub-levels
    }
    kotlinOptions { jvmTarget = "17" }

    // Wallpapers are intended to ship as a downloadable asset pack rather than in the base APK,
    // so the install stays small and the ~150 MB of artwork streams on demand.
    //
    // The pack is NOT wired up yet, deliberately: there is no artwork to put in it, and an empty
    // asset pack fails `bundleRelease` with a confusing error while adding nothing. Re-enable when
    // the artwork is delivered by creating a `wallpaper_pack` module containing only:
    //
    //     plugins { id("com.android.asset-pack") }
    //     assetPack {
    //         packName.set("wallpaper_pack")
    //         dynamicDelivery { deliveryType.set("fast-follow") }
    //     }
    //
    // then adding `include(":wallpaper_pack")` to settings.gradle.kts and restoring the line below.
    //
    // assetPacks += listOf(":wallpaper_pack")
}

dependencies {
    implementation(project(":core:model"))
    implementation(project(":core:design"))
    implementation(project(":core:render"))
    implementation(project(":core:data"))
    implementation(project(":feature:catalog"))
    implementation(project(":feature:editor"))
    implementation(project(":feature:wallpapers"))
    implementation(project(":feature:settings"))
    implementation(project(":widget"))

    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.material3)
    implementation(libs.activity.compose)
    // Provides Theme.SplashScreen, the parent of Theme.Prism.Splash in themes.xml.
    implementation(libs.core.splashscreen)
    implementation(libs.navigation.compose)
    implementation(libs.hilt.android)
    implementation(libs.hilt.navigation.compose)
    implementation(libs.billing.ktx)
    // RenderModule provides PrismDatabase; PrismApp implements Configuration.Provider.
    implementation(libs.room.runtime)
    implementation(libs.room.ktx)
    implementation(libs.work.runtime)
    implementation(libs.hilt.work)
    ksp(libs.hilt.compiler)
    // @HiltWorker is generated by androidx.hilt:hilt-compiler, a separate
    // processor from Dagger's hilt-android-compiler. Both are required.
    ksp(libs.androidx.hilt.compiler)

    testImplementation(libs.junit)
    testImplementation(libs.truth)
    testImplementation(libs.robolectric)

    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.3")
}
