#!/usr/bin/env python3
"""
Structural checker for the Prism sources.

Not a Kotlin compiler — it cannot resolve types or check signatures. It catches the classes of
defect that are cheap to find without one and expensive to find by eye across 60 files: unbalanced
delimiters, duplicate top-level declarations, references to symbols that exist nowhere in the tree,
imports of packages not in any module's dependency list, and leftover TODO markers.

Everything it reports is a real problem. Everything it stays silent about may still be a problem —
that is what the compiler is for, and it has not run yet.
"""
import re, sys, glob, os
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KT = sorted(glob.glob(f"{ROOT}/**/*.kt", recursive=True))

issues = []

def add(path, line, kind, msg):
    issues.append((kind, f"{os.path.relpath(path, ROOT)}:{line}: {msg}"))

# ---- pass 1: collect declarations -----------------------------------------------------------
decls = defaultdict(list)          # simple name -> [(path, kind)]
DECL = re.compile(r'^\s*(?:internal |private |public |abstract |open |sealed |data |value |@\w+\s+)*'
                  r'(class|object|interface|enum class|fun|val)\s+([A-Za-z_]\w*)')
for path in KT:
    for i, line in enumerate(open(path), 1):
        m = DECL.match(line)
        if m and m.group(1) in ("class", "object", "interface", "enum class"):
            decls[m.group(2)].append((path, m.group(1)))

# duplicate top-level types
for name, sites in decls.items():
    if len(sites) > 1:
        paths = {p for p, _ in sites}
        if len(paths) > 1:
            add(sites[0][0], 0, "DUPLICATE",
                f"type '{name}' declared in {len(paths)} files: "
                + ", ".join(sorted(os.path.basename(p) for p in paths)))

# ---- pass 2: per-file structural checks -----------------------------------------------------
KNOWN_EXTERNAL = ("android.", "androidx.", "kotlin", "java.", "javax.", "dagger.", "com.google.",
                  "com.android.", "org.jetbrains.", "org.junit", "org.robolectric")

for path in KT:
    src = open(path).read()
    lines = src.splitlines()

    # delimiter balance, ignoring strings and comments (crude but catches truncated files)
    stripped = re.sub(r'"""[\s\S]*?"""', '""', src)
    stripped = re.sub(r'"(?:\\.|[^"\\])*"', '""', stripped)
    stripped = re.sub(r'//[^\n]*', '', stripped)
    stripped = re.sub(r'/\*[\s\S]*?\*/', '', stripped)
    for open_c, close_c, label in (("{", "}", "braces"), ("(", ")", "parens"), ("[", "]", "brackets")):
        d = stripped.count(open_c) - stripped.count(close_c)
        if d:
            add(path, 0, "BALANCE", f"{label} unbalanced by {d:+d}")

    # Duplicate imports of the same simple name. Aliased imports (`as Foo`) are excluded, since
    # aliasing is the correct way to import two same-named types.
    plain = [l for l in re.findall(r'^import\s+([\w.]+)\s*$', src, re.M)]
    seen = {}
    for imp in plain:
        simple = imp.split('.')[-1]
        if simple in seen and seen[simple] != imp:
            add(path, 0, "IMPORT", f"ambiguous: '{simple}' imported from both {seen[simple]} and {imp}")
        elif simple in seen:
            add(path, 0, "IMPORT", f"duplicate import: {imp}")
        seen[simple] = imp

    # project imports must resolve to a declaration somewhere in the tree
    for i, line in enumerate(lines, 1):
        m = re.match(r'\s*import\s+(com\.prism\.studio\.[\w.]+)', line)
        if m:
            symbol = m.group(1).split('.')[-1] or ''
            if not symbol: continue
            # R is always generated by AGP. BuildConfig is NOT: since AGP 8 it exists only when
            # the module sets `buildFeatures { buildConfig = true }`, and assuming otherwise hid a
            # real "Unresolved reference 'BuildConfig'" for a whole build cycle.
            if symbol == "R": continue
            if symbol == "BuildConfig":
                module = path
                while module != ROOT and not os.path.exists(os.path.join(module, "build.gradle.kts")):
                    module = os.path.dirname(module)
                gradle = os.path.join(module, "build.gradle.kts")
                enabled = os.path.exists(gradle) and "buildConfig = true" in open(gradle).read()
                if not enabled:
                    add(path, i, "UNRESOLVED",
                        "uses BuildConfig, but this module does not set buildFeatures { buildConfig = true }")
                continue
            if symbol[0].isupper() and symbol not in decls:
                # could be an enum entry or a top-level val/fun import
                if not re.search(rf'\b(val|fun|enum class|object|data class|class|interface)\s+{symbol}\b', src):
                    found = any(re.search(rf'\b(val|fun|class|object|interface)\s+{symbol}\b', open(p).read()) for p in KT)
                    if not found:
                        add(path, i, "UNRESOLVED", f"import of '{symbol}' — no declaration found in the tree")

        # `const val` initializers must be compile-time constants; a function call is not one.
        if re.search(r'\bconst\s+val\s+\w+\s*=.*\w\s*\(', line) and "//" not in line.split("=")[0]:
            add(path, i, "CONST", "const val initializer contains a call: " + line.strip()[:70])

        # Compose property delegates need their operator extensions imported, or Kotlin dumps
        # every getValue candidate in scope and the real cause is buried.
        if re.search(r'\bvar\s+\w+\s+by\s+', line) and "androidx.compose" in src:
            if "import androidx.compose.runtime.getValue" not in src:
                add(path, i, "DELEGATE", "`var ... by` without importing androidx.compose.runtime.getValue")
            if "import androidx.compose.runtime.setValue" not in src:
                add(path, i, "DELEGATE", "`var ... by` without importing androidx.compose.runtime.setValue")

        # Extension functions cannot be called fully-qualified without a receiver.
        # `.androidx.compose.foundation.background(...)` and
        # `androidx.compose.foundation.clickable(...)` have each broken a build once.
        m = re.search(r'\.\s*$|^\s*\.(androidx|kotlinx|com)\.', line)
        if re.match(r'\s*\.[a-z]+\.[a-z]+\.', line) or \
           re.search(r'=\s*androidx\.compose\.(foundation|ui)\.[a-z]\w*\(', line):
            add(path, i, "EXTENSION",
                "fully-qualified call to what is probably an extension function: " + line.strip()[:70])

        # Compose runtime symbols used without their import. The compiler reports this as
        # "Unresolved reference", and it has now cost one build cycle.
        for sym in ("mutableStateOf", "mutableIntStateOf", "mutableFloatStateOf",
                    "derivedStateOf", "rememberCoroutineScope", "rememberUpdatedState"):
            if re.search(rf'\b{sym}\s*[({{]', line) and "import" not in line:
                if f"androidx.compose.runtime.{sym}" not in src and "androidx.compose.runtime.*" not in src:
                    add(path, i, "COMPOSE-IMPORT", f"uses {sym} without importing it")

        if "TODO(" in line or re.search(r'//\s*TODO', line):
            add(path, i, "TODO", line.strip()[:90])
        if re.search(r'\bLog\.[dv]\(', line):
            add(path, i, "DEBUG", "debug logging left in source")

    # a Compose file importing Modifier must import androidx.compose.ui.Modifier
    if "Modifier." in src and "import androidx.compose.ui.Modifier" not in src and "compose" in src:
        if re.search(r'modifier:\s*Modifier', src):
            add(path, 0, "IMPORT", "uses Modifier without importing androidx.compose.ui.Modifier")

# ---- pass 2b: exhaustive `when` over sealed types ----------------------------------------------
# Kotlin requires a `when` used as an expression over a sealed type to cover every subtype. Adding a
# subtype silently breaks every such `when` in the codebase, and the compiler reports it one file at
# a time. This finds them all at once.
SEALED = {}
for path in KT:
    src = open(path).read()
    for m in re.finditer(r'sealed (?:interface|class) (\w+)', src):
        parent = m.group(1)
        subs = set()
        # Declarations routinely span several lines:
        #     data class Clock(
        #         val now: LocalDateTime,
        #     ) : WidgetData
        # so scan from each `data class`/`data object` to its supertype rather than matching a
        # single line. Getting this wrong is why the first version of this check silently passed.
        for d in re.finditer(r'\bdata (?:class|object) (\w+)', src):
            tail = src[d.end():d.end() + 600]
            head = tail.split("data class")[0].split("data object")[0]
            # The colon must be in supertype position — after the constructor's `)` for a data
            # class, or straight after the name for a data object. Matching a bare `: Parent`
            # also matched property declarations like `val surface: Surface`, which attributed
            # WidgetStyle to Surface and produced three false positives.
            if re.search(rf'\)\s*:\s*{parent}\b', head) or re.search(rf'^\s*:\s*{parent}\b', head) \
                    or re.match(rf'\s*:\s*{parent}\b', head):
                subs.add(d.group(1))
        if subs:
            SEALED[parent] = subs

for path in KT:
    src = open(path).read()
    for parent, subs in SEALED.items():
        used = set(re.findall(rf'is {parent}\.(\w+)', src))
        if len(used) < 2:
            continue
        if "else ->" in src:
            # Imprecise: an `else` anywhere in the file suppresses. Only ever hides a finding,
            # never invents one.
            continue
        missing = subs - used - {"None"}
        if missing:
            add(path, 0, "EXHAUSTIVE",
                f"`when` over sealed {parent} is missing: {', '.join(sorted(missing))}")

def strip_comments(src):
    src = re.sub(r'/\\*[\\s\\S]*?\\*/', '', src)
    return re.sub(r'//[^\\n]*', '', src)

# ---- pass 2c: trailing lambda binding to `modifier` --------------------------------------------
# Compose convention makes `modifier` the last parameter, so `Foo(a, b) { ... }` binds the lambda to
# it rather than to the onClick you meant. The compiler reports this as a confusing pair of errors
# about Function0 vs Modifier.
COMPOSABLES_ENDING_IN_MODIFIER = set()
for path in KT:
    src = strip_comments(open(path).read())
    for m in re.finditer(r'fun (\w+)\(([\s\S]*?)\)\s*\{', src):
        params = m.group(2)
        if re.search(r'modifier:\s*Modifier[^,]*,?\s*$', params.strip()) and "onClick" in params:
            COMPOSABLES_ENDING_IN_MODIFIER.add(m.group(1))

for path in KT:
    src = strip_comments(open(path).read())
    for name in COMPOSABLES_ENDING_IN_MODIFIER:
        for m in re.finditer(rf'\b{name}\([^()\n]*\)\s*\{{', src):
            line = src[:m.start()].count("\n") + 1
            add(path, line, "TRAILING-LAMBDA",
                f"{name}(...) {{ }} binds the lambda to `modifier`, not `onClick` — pass onClick by name")

# ---- pass 2d: BuildConfig requires an opt-in ---------------------------------------------------
# AGP 8 generates BuildConfig only when buildFeatures.buildConfig is true. Referencing it without
# that flag is "Unresolved reference: BuildConfig", which looks like a missing import and is not.
for path in KT:
    src = open(path).read()
    if not re.search(r'\bBuildConfig\.', src):
        continue
    module = os.path.relpath(path, ROOT).split(os.sep)
    for depth in (2, 1):
        build_file = os.path.join(ROOT, *module[:depth], "build.gradle.kts")
        if os.path.isfile(build_file):
            if "buildConfig = true" not in open(build_file).read():
                add(path, 0, "BUILDCONFIG",
                    f"references BuildConfig but {os.path.relpath(build_file, ROOT)} "
                    f"does not set buildFeatures.buildConfig = true")
            break

# ---- pass 3: dependency sanity ---------------------------------------------------------------
for build in glob.glob(f"{ROOT}/*/build.gradle.kts") + glob.glob(f"{ROOT}/*/*/build.gradle.kts"):
    module_dir = os.path.dirname(build)
    deps = open(build).read()
    src_files = glob.glob(f"{module_dir}/src/main/**/*.kt", recursive=True)
    uses = "".join(open(f).read() for f in src_files)
    checks = [
        ("androidx.core.graphics", "core.ktx", "core-ktx"),
        ("androidx.room", "room", "room"),
        ("javax.inject", "hilt", "hilt"),
        ("kotlinx.serialization", "serialization", "serialization"),
        ("androidx.work", "work", "work"),
    ]
    # java.time on minSdk 26 needs core library desugaring, and AGP needs both the flag and the
    # dependency — either alone silently does nothing, so the failure is a runtime crash on an old
    # device rather than a build error.
    if "java.time" in uses:
        if "isCoreLibraryDesugaringEnabled" not in deps or "coreLibraryDesugaring(" not in deps:
            add(build, 0, "DEPENDENCY",
                "module uses java.time but does not enable core library desugaring "
                "(needs both isCoreLibraryDesugaringEnabled and the coreLibraryDesugaring dependency)")

    for pkg, needle, label in checks:
        # `needle` matches either a literal coordinate or a version-catalog alias (libs.core.ktx).
        if pkg in uses and needle not in deps and needle.replace(".", "-") not in deps:
            add(build, 0, "DEPENDENCY",
                f"module uses {pkg} but its build file declares no {label} dependency")

by_kind = defaultdict(list)
for kind, msg in issues:
    by_kind[kind].append(msg)

order = ["BALANCE", "DUPLICATE", "EXHAUSTIVE", "CONST", "DELEGATE", "EXTENSION", "TRAILING-LAMBDA", "COMPOSE-IMPORT", "BUILDCONFIG", "UNRESOLVED", "DEPENDENCY", "IMPORT", "TODO", "DEBUG"]
total = 0
for kind in order:
    if kind in by_kind:
        print(f"\n== {kind} ({len(by_kind[kind])}) ==")
        for msg in sorted(set(by_kind[kind])):
            print("  " + msg)
        total += len(by_kind[kind])

unprinted = set(by_kind) - set(order)
if unprinted:
    raise SystemExit(f"static_check bug: issue kinds not in the print order: {sorted(unprinted)}")

print(f"\n{len(KT)} Kotlin files checked, {total} issues found.")
sys.exit(1 if total else 0)
